[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200
  force = true

[[redirects]]
  from = "/faq.html"
  to = "/faq.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200